swagger: "2.0"
info:
  title: Link Management API
  version: 1.0.0
  description: API for managing links.
paths:
  /links:
    post:
      summary: Create a new link
      parameters:
        - name: link
          in: body
          required: true
          schema:
            $ref: "#/definitions/Link"
      responses:
        201:
          description: Link created successfully
    get:
      summary: Get all links
      responses:
        200:
          description: List of all links
  /links/{id}:
    get:
      summary: Get a link by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Link found
    put:
      summary: Update a link by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: link
          in: body
          required: true
          schema:
            $ref: "#/definitions/Link"
      responses:
        200:
          description: Link updated successfully
    delete:
      summary: Delete a link by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Link deleted successfully
definitions:
  Link:
    type: object
    properties:
      id:
        type: integer
      url:
        type: string
      title:
        type: string
